name: publish_docs

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'

jobs:
  publish_docs:
    if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
    runs-on: ubuntu-latest
    steps:
      - name: Prepare branch name
        run: >
          echo "refName=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Checkout relevant branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.refName }}
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: target/gh-pages
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Run docs generation
        run: >
          ./mvnw --no-transfer-progress asciidoctor:process-asciidoc@generate-docs -pl org.neo4j:neo4j-cypher-dsl-parent -Dproject.build.docs=target/gh-pages/${refName} &&
          ./mvnw --no-transfer-progress site -pl org.neo4j:neo4j-cypher-dsl -am &&
          rm -rf target/gh-pages/${refName}/project-info &&
          mv neo4j-cypher-dsl/target/site target/gh-pages/${refName}/project-info
      - name: Create symlink
        if: (github.event_name == 'create' && github.event.ref_type == 'tag')
        working-directory: ./target/gh-pages
        run: ln -sfn ${refName} current
      - name: Commit to gh-pages
        working-directory: ./target/gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update GH-Pages."
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: target/gh-pages
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
